name: ziziphora
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design:
    true

    # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Inter
      fonts:
        - asset: ./assets/fonts/Inter/Inter-Regular.ttf
        - asset: ./assets/fonts/Inter/Inter-Italic.ttf
          style: italic
        - asset: ./assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: ./assets/fonts/Inter/Inter-SemiBoldItalic.ttf
          style: italic
        - asset: ./assets/fonts/Inter/Inter-Bold.ttf
          weight: 700

    - family: Persian
      fonts:
        - asset: ./assets/fonts/Persian/Iranyekan.ttf
        - asset: ./assets/fonts/Persian/Iranyekan-Bold.ttf
          weight: 700
